import { Heebo, Signika } from "next/font/google";
import "./globals.css";

const heebo = Heebo({
  subsets: ["latin"],
  variable: "--font-heebo",
});

const signika = Signika({
  subsets: ["latin"],
  variable: "--font-signika",
});

export const metadata = {
  title: "Astroplate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${heebo.variable} ${signika.variable}`}>
      <body>{children}</body>
    </html>
  );
}
